version: '3'

services:
    app:
        container_name: precpago-api
        build:
            context: ./
            dockerfile: Dockerfile
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '80:80'
        volumes:
            - ./src:/var/www/html
            